- name: Install Java
  hosts: testservers
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      yum:
        update_cache: yes
    - name: Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - default-jdk
