- name: sample shellscript playrun
  hosts: testservers
  remote_user: jacky
  become: true
  
  tasks:
    - name: run my shell script
      script: ostype.sh
      register: script_output
      args:
        executable: /bin/bash
      
      
    - debug: msg="{{script_output.stdout}}"
