- name: sample shellscript playrun
  hosts: testservers
  become: true
 
  tasks:
    - name: run my shell script
      script: ~/.ssh/AnsibleHandson/ostype.sh
      args:
        executable: /bin/bash
      register: script_output
    - debug: msg="{{script_output.stdout}}"
