- name: sample shellscript playrun
  hosts: testservers
  remote_user: jacky
  become: true
  
  tasks:
    - name: run my shell script
      script: ostype.sh
      args:
        executable: /bin/bash
