- name: UnInstall Java
  hosts: testservers
  become: true
  tasks:
    - name: UnInstall Java using Ansible
      become_user: root
      become_method: sudo
      apt:
        purge: yes
        pkg: "{{ packages }}"
        state: absent
      vars:
        packages:
           - java-1.8.0-openjdk
