- name: UnInstall Java
  hosts: testservers
  become: true
  tasks:
    - name: UnInstall Java using Ansible
      become_user: root
      become_method: sudo
      yum:
        pkg: "{{ packages }}"
        state: absent
      vars:
        packages:
           - /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312*
