- name: UnInstall Java
  hosts: testservers
  become: yes
  tasks:
    - name: UnInstall Java using Ansible
      become_user: root
      become_method: sudo
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
           - java-1.8.0-openjdk
